# Generated by Django 3.0.5 on 2024-08-28 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0006_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='added_at',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
    ]
