# Generated by Django 3.0.5 on 2024-08-29 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0009_auto_20240829_2324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='customer',
            new_name='user',
        ),
    ]
