# Generated by Django 3.0.5 on 2024-08-29 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0010_auto_20240829_2347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='customer',
        ),
    ]
