# Generated by Django 3.0.5 on 2024-09-01 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0014_auto_20240901_2014'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
